kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: webserver-api
  labels:
    app.kubernetes.io/instance: 2-webserver
  annotations:
    haproxy.router.openshift.io/set-forwarded-headers: append
spec:
  host: webserver-api-demo.apps.ocp.superjkdevops.com.pl
  to:
    kind: Service
    name: webserver-api
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
